blogapp/urls.py
from django.urls import path
from .views import *


app_name="blogapp"
urlpatterns=[
	path("",HomeView.as_view()),
	path("contact/",ContactView.as_view()),
	path("about/",AboutView.as_view()),
	path("gallery/",GalleryView.as_view()),
	path("services/",ServicesView.as_view()),
	path("register/",RegistrationView.as_view(),name="registration"),
	#path("event/",PostView.as_view()),
	path("blog/",BlogListView.as_view()),
	path("career/",CareerView.as_view()),
	# path("survey/",SurveyView.as_view()),
	path("products/",ProductsView.as_view()),
	path("blog/<int:pk>/detail/",BlogDetailView.as_view()),
	path("create/",BlogCreateView.as_view()),
	path("create/post/",PostCreateView.as_view()),
	path("post/<int:pk>/detail/",PostDetailView.as_view()),
	path("post/",PostListView.as_view()),
	path("blog/<int:pk>/update/",BlogUpdateView.as_view()),
	path("post/<int:pk>/update/",PostUpdateView.as_view()),
	path("photocreate/",PhotoCreateView.as_view()),
	path("photo/<int:pk>/detail/",PhotoDetailView.as_view()),
	

]

blogproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blogapp.urls")),

]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models

from django.contrib.auth.models import User



STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now_add= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title


class Blog(models.Model):
    title=models.CharField(max_length=500)
    image=models.ImageField(upload_to="blogs")
    description=models.TextField()
    author=models.CharField(max_length=50)
    published_on=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title


class Photo(models.Model):
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to="photos")

    def __str__(self):
        return self.title



class Message(models.Model):
    sender=models.CharField(max_length=200)
    email=models.EmailField(null=True,blank=True)
    mobile=models.CharField(max_length=50)
    subject=models.CharField(max_length=200)
    text=models.TextField()
    date=models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.sender

blogapp/forms.py
from django import forms

from .models import *



class BlogForm(forms.ModelForm):
	class Meta:
		model=Blog
		fields=['title','image','description','author']




class PostForm(forms.ModelForm):
	class Meta:
		model=Post
		fields="__all__"


class PhotoForm(forms.ModelForm):
	class Meta:
		model=Photo
		fields="__all__"


class ContactForm(forms.Form):
	fullname=forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control",

		"placeholder":"Enter your full name",}))
	email=forms.EmailField(required=False,widget=forms.EmailInput(attrs={
		"class":"form-control",

		"placeholder":"Email",}))
	mobile=forms.CharField(widget=forms.NumberInput(attrs={
		"class":"form-control",

		"placeholder":"Phone number",}))
	subject=forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control",

		"placeholder":"Subject",}))
	message=forms.CharField(widget=forms.Textarea(attrs={
		"class":"form-control",

		"placeholder":"Type your message",
		"rows":5,

		}))




class RegistrationForm(forms.Form):
	email=forms.EmailField(widget=forms.EmailInput())
	password=forms.CharField(widget=forms.PasswordInput())
	confirm_password=forms.CharField(widget=forms.PasswordInput())










# class SurveyForm(forms.Form):
# 	fullname=forms.CharField(widget=forms.TextInput(attrs={
# 		"class":"form-control",

# 		"placeholder":"Enter your full name",}))

# 	email=forms.EmailField(required=False,widget=forms.EmailInput(attrs={
# 		"class":"form-control",

# 		"placeholder":"Email",}))

# 	How_old_are_you: =forms.CharField(widget=forms.NumberInput(attrs={
# 		"class":"form-control",

# 		"placeholder":"Enter your age",}))

blogapp/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import *
from .models import *
from .forms import *

class HomeView(TemplateView):
	template_name="home.html"



class ContactView(FormView):
	template_name="contact.html"
	form_class=ContactForm
	success_url="/"


	def form_valid(self,form):
		nam=form.cleaned_data["fullname"]
		eml=form.cleaned_data["email"]
		mbl=form.cleaned_data["mobile"]
		sub=form.cleaned_data['subject']
		message=form.cleaned_data['message']
		Message.objects.create(sender=nam,email=eml,mobile=mbl,subject=sub,text=message)

		return super().form_valid(form)


class AboutView(TemplateView):
	template_name="about.html"


class GalleryView(TemplateView):
	template_name="gallery.html"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['allphotos'] = Photo.objects.all().order_by('-id')
		
		return context
	



class PhotoDetailView(DetailView):
	template_name="photodetail.html"
	model=Photo
	context_object_name="photoobject"


# class EventView(TemplateView):
# 	template_name="event.html"

class BlogListView(ListView):
	template_name="blog.html"
	queryset=Blog.objects.all().order_by("-id")
	context_object_name="allblogs"



class BlogDetailView(DetailView):
	template_name="blogdetail.html"
	model=Blog
	context_object_name="blogobject"

class CareerView(TemplateView):
	template_name="career.html"


# class SurveyView(FormView):
# 	template_name="survey.html"
# 	form_class=SurveyForm
# 	success_url="/"


# 	def form_valid(self,form):
# 		nam=form.cleaned_data["fullname"]
# 		eml=form.cleaned_data["email"]
# 		mbl=form.cleaned_data["mobile"]
# 		sub=form.cleaned_data['subject']
# 		message=form.cleaned_data['message']
# 		Message.objects.create(sender=nam,email=eml,mobile=mbl,subject=sub,text=message)

# 		return super().form_valid(form)



class ServicesView(TemplateView):
	template_name="services.html"


class ProductsView(TemplateView):
	template_name="products.html"


class BlogCreateView(CreateView):
	template_name="create.html"
	form_class=BlogForm
	success_url="/blog/"


class PostListView(ListView):
	template_name="post.html"
	queryset=Post.objects.all().order_by("-id")
	context_object_name="allposts"



class BlogUpdateView(UpdateView):
	template_name="create.html"
	form_class=BlogForm
	success_url="/blog/"
	model=Blog
	queryset=Blog.objects.all()



class PostDetailView(DetailView):
	template_name="postdetail.html"
	model=Post
	context_object_name="postobject"



class PostUpdateView(UpdateView):
	template_name="postcreate.html"
	form_class=PostForm
	success_url="/post/"
	model=Post
	queryset=Post.objects.all()



class PostCreateView(CreateView):
	template_name="postcreate.html"
	form_class=PostForm
	success_url="/post/"




class PhotoCreateView(CreateView):
	template_name="photocreate.html"
	form_class=PhotoForm
	success_url="/gallery/"


class RegistrationView(FormView):
	template_name="register.html"
	form_class=RegistrationForm
	success_url="/"

templates/about.html
{% extends 'base.html' %}



{% block content %}

<iframe src="https://www.escapehimalaya.com/natural-wonders-nepal/" height="8000" width="1335"></iframe>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
  <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/deco.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body class="">
	<div class="topnav">
	<a class="active" href="/">Home</a>
  <a href="/blog/">Blogs</a>
  <a href="/contact/">Contact</a>
  <a href="/about/">About</a>
  <a href="/post/">Posts</a>
  <a href="/gallery/">Gallery</a>
  <a href="/products/">Products</a>
  <!-- <a href="/survey/">Survey</a> -->
  <a href="/services/">Services</a>
  <a href="/career/">Career</a>
  <!-- <a href="/create/">Create</a> -->
  
  	</div>
<h1 style="color:blue">Welcome to my website</h1>
<div class="container-fluid">
  
{% block content %}
{% endblock %}
</div>
</body>
</html>

templates/blogdetail.html
{% extends 'base.html' %}



{% block content %}
<a href="/blog/"><button>Back</button></a>
<h2>{{blogobject.title}}</h2>
<p>Published on:<b>{{blogobject.published_on}}</b></p>
<img src="{{blogobject.image.url}}" width="400" >
<p>{{blogobject.description}}</p>
<hr>
<p>Author:{{blogobject.author}}</p>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block title %}
       	Contact-Us
		{% endblock %}


{% block content %}
<div class="row">
	<div class="col-md-4 mx-auto">
		<b><u>Contact-Us</u></b>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-info">Contact</button>
		</form>
		
	</div>
	
</div>


{% endblock %}

templates/create.html
{% extends 'base.html' %}



{% block content %}
<h2>Blog Form</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button>Submit Data</button>
</form>

{% endblock %}

templates/gallery.html
{% extends 'base.html' %}



{% block content %}
<a href="/photocreate/"><button>Upload Photo</button></a><hr>
<div class="row">
{% for i in allphotos %}
<div class="col-md-3">
<a href="{{i.image.url}}" target="_blank"><img src="{{i.image.url}}" style="height: 250px; width: 200px;  object-fit: cover;"></a>
</div>
{% endfor %}
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}



{% block content %}
<h3>this is content of home page</h3>


{% endblock %}

templates/photocreate.html
{% extends 'base.html' %}



{% block content %}
<h2>Photo Form</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button>Submit</button>
</form>

{% endblock %}

templates/photodetail.html
{% extends "base.html" %}
{% block content %}

<h3>Photos</h3>
<div class="row">
{% for pht in photoobject.photo_set.all %}
 <div class="col-md-3">
<img src="{{pht.image.url}}" class="img-fluid"  style="height: 200px; object-fit: cover">
<p><b>{{pht.title}}</b></p>
</div>
{% endfor %}
</div>
{% endblock %}

templates/post.html
{% extends 'base.html' %}



{% block content %}
<h2>All Posts</h2>
<a href="/create/post/">Create Post</a>
{% for i in allposts %}
<b><li><a href="/post/{{i.id}}/detail/">{{i.title}}</a><a href="/post/{{i.id}}/update/">            Update</a></li></b>
<b><p>{{i.created_on}}</p></b>
{% endfor %}
{% endblock %}

templates/postcreate.html
{% extends 'base.html' %}



{% block content %}
<h2>Post Form</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button>Submit Data</button>
</form>

{% endblock %}

templates/postdetail.html
{% extends 'base.html' %}



{% block content %}
<h2>{{postobject.title}}</h2>
<p>Published on:<b>{{postobject.created_on}}</b></p>
<p>{{postobject.content}}</p>
<hr>
<p>Author:{{postobject.author}}</p>

{% endblock %}

templates/register.html
{% extends 'base.html' %}



{% block content %}
<h2>Registration Form</h2>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="btn btn-primary">Submit</button>
</form>

{% endblock %}

templates/services.html
{% extends 'base.html' %}



{% block content %}
<h3>this is content of services page</h3>


{% endblock %}